name: calendar_planner
description: A Flutter calendar planner app with reminders.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <4.0.0'
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Calendar widget
  table_calendar: ^3.0.9
  
  # Local database
  sqflite: ^2.3.0
  path: ^1.8.3
  
  # Local notifications
  flutter_local_notifications: ^15.1.0+1
  timezone: ^0.9.2
  permission_handler: ^11.0.1
  
  # Date formatting
  intl: ^0.18.1
  
  # UI components
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  # Add assets if needed
  # assets:
  #   - images/
  
  # Add fonts if needed
  # fonts:
  #   - family: Roboto
  #     fonts:
  #       - asset: fonts/Roboto-Regular.ttf